INFO:app:{'qq': 'pp', 'qwdqwd': 123}
ERROR:app:Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\yujd1\Documents\GitHub\datascience\milestone3\serving\app.py", line 112, in predict
    raise NotImplementedError("TODO: implement this enpdoint")
NotImplementedError: TODO: implement this enpdoint
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:01:43] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
INFO:app:{'qq': 'pp'}
ERROR:app:Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\yujd1\Documents\GitHub\datascience\milestone3\serving\app.py", line 112, in predict
    raise NotImplementedError("TODO: implement this enpdoint")
NotImplementedError: TODO: implement this enpdoint
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:02:27] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
INFO:app:qq
ERROR:app:Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\yujd1\Documents\GitHub\datascience\milestone3\serving\app.py", line 112, in predict
    raise NotImplementedError("TODO: implement this enpdoint")
NotImplementedError: TODO: implement this enpdoint
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:02:39] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
INFO:app:qq
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:03:02] "POST /predict HTTP/1.1" 200 -
INFO:app:{'qq': 'pp', 'qwdqwd': 123}
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:03:10] "POST /predict HTTP/1.1" 200 -
INFO:app:{'url': ''}
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:04:03] "POST /predict HTTP/1.1" 200 -
INFO:app:{'url': ''}
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:04:09] "POST /predict HTTP/1.1" 200 -
INFO:app:{'url': ''}
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:04:15] "POST /predict HTTP/1.1" 200 -
ERROR:app:Exception on /logs [GET]
Traceback (most recent call last):
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\yujd1\Documents\GitHub\datascience\milestone3\serving\app.py", line 53, in logs
    raise NotImplementedError("TODO: implement this endpoint")
NotImplementedError: TODO: implement this endpoint
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:07:12] "[35m[1mGET /logs HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:07:35] "GET /logs HTTP/1.1" 200 -
ERROR:app:Exception on /logs [GET]
Traceback (most recent call last):
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\yujd1\Documents\GitHub\datascience\milestone3\serving\app.py", line 63, in logs
    return jsonify(response)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "C:\ProgramData\miniconda3\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 51, in default
    return super().default(o)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:15:49] "[35m[1mGET /logs HTTP/1.1[0m" 500 -
ERROR:app:Exception on /logs [GET]
Traceback (most recent call last):
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\yujd1\Documents\GitHub\datascience\milestone3\serving\app.py", line 63, in logs
    return jsonify(response)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "C:\ProgramData\miniconda3\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 51, in default
    return super().default(o)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:16:31] "[35m[1mGET /logs HTTP/1.1[0m" 500 -
ERROR:app:Exception on /logs [GET]
Traceback (most recent call last):
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\yujd1\Documents\GitHub\datascience\milestone3\serving\app.py", line 63, in logs
    return jsonify(response)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "C:\ProgramData\miniconda3\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 51, in default
    return super().default(o)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:16:39] "[35m[1mGET /logs HTTP/1.1[0m" 500 -
ERROR:app:Exception on /logs [GET]
Traceback (most recent call last):
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\yujd1\Documents\GitHub\datascience\milestone3\serving\app.py", line 63, in logs
    return jsonify(response)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "C:\ProgramData\miniconda3\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 51, in default
    return super().default(o)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:17:27] "[35m[1mGET /logs HTTP/1.1[0m" 500 -
ERROR:app:Exception on /logs [GET]
Traceback (most recent call last):
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\yujd1\Documents\GitHub\datascience\milestone3\serving\app.py", line 63, in logs
    return jsonify(response)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "C:\ProgramData\miniconda3\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 51, in default
    return super().default(o)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:19:26] "[35m[1mGET /logs HTTP/1.1[0m" 500 -
ERROR:app:Exception on /logs [GET]
Traceback (most recent call last):
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\yujd1\Documents\GitHub\datascience\milestone3\serving\app.py", line 63, in logs
    return jsonify(response)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "C:\ProgramData\miniconda3\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 51, in default
    return super().default(o)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:19:59] "[35m[1mGET /logs HTTP/1.1[0m" 500 -
ERROR:app:Exception on /logs [GET]
Traceback (most recent call last):
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\yujd1\Documents\GitHub\datascience\milestone3\serving\app.py", line 63, in logs
    return jsonify(response)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "C:\ProgramData\miniconda3\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 51, in default
    return super().default(o)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:20:55] "[35m[1mGET /logs HTTP/1.1[0m" 500 -
ERROR:app:Exception on /logs [GET]
Traceback (most recent call last):
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\yujd1\Documents\GitHub\datascience\milestone3\serving\app.py", line 63, in logs
    return jsonify(response)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "C:\ProgramData\miniconda3\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 51, in default
    return super().default(o)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:21:05] "[35m[1mGET /logs HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:22:28] "GET /logs HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:22:34] "GET /logs HTTP/1.1" 200 -
INFO:app:{'url': ''}
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:22:40] "POST /predict HTTP/1.1" 200 -
ERROR:app:Exception on /logs [GET]
Traceback (most recent call last):
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\yujd1\Documents\GitHub\datascience\milestone3\serving\app.py", line 63, in logs
    return jsonify(response)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "C:\ProgramData\miniconda3\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 51, in default
    return super().default(o)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:22:56] "[35m[1mGET /logs HTTP/1.1[0m" 500 -
ERROR:app:Exception on /logs [GET]
Traceback (most recent call last):
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\yujd1\Documents\GitHub\datascience\milestone3\serving\app.py", line 63, in logs
    return jsonify(response)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "C:\ProgramData\miniconda3\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 51, in default
    return super().default(o)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:23:39] "[35m[1mGET /logs HTTP/1.1[0m" 500 -
ERROR:app:Exception on /logs [GET]
Traceback (most recent call last):
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\yujd1\Documents\GitHub\datascience\milestone3\serving\app.py", line 63, in logs
    return jsonify(response)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "C:\ProgramData\miniconda3\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 51, in default
    return super().default(o)
  File "C:\ProgramData\miniconda3\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:23:57] "[35m[1mGET /logs HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:24:02] "GET /logs HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:25:37] "GET /logs HTTP/1.1" 200 -
INFO:app:logs read.
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:25:48] "GET /logs HTTP/1.1" 200 -
INFO:app:{'url': ''}
ERROR:app:Exception on /download_registry_model [POST]
Traceback (most recent call last):
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\yujd1\Documents\GitHub\datascience\milestone3\serving\app.py", line 97, in download_registry_model
    model_name = json["model_name"]
KeyError: 'model_name'
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:53:16] "[35m[1mPOST /download_registry_model HTTP/1.1[0m" 500 -
INFO:app:{'url': ''}
ERROR:app:Exception on /download_registry_model [POST]
Traceback (most recent call last):
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\yujd1\Documents\GitHub\datascience\milestone3\serving\app.py", line 97, in download_registry_model
    model_name = json["model_name"]
KeyError: 'model_name'
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:53:53] "[35m[1mPOST /download_registry_model HTTP/1.1[0m" 500 -
INFO:app:{'url': 'ffff'}
ERROR:app:Exception on /download_registry_model [POST]
Traceback (most recent call last):
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\yujd1\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\yujd1\Documents\GitHub\datascience\milestone3\serving\app.py", line 97, in download_registry_model
    model_name = json["model_name"]
KeyError: 'model_name'
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:54:57] "[35m[1mPOST /download_registry_model HTTP/1.1[0m" 500 -
INFO:app:logs read.
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:55:24] "GET /logs?model=qq&version=pp HTTP/1.1" 200 -
INFO:app:logs read.
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:55:35] "GET /logs?model_name=qq&version=pp HTTP/1.1" 200 -
INFO:app:{'model_name': 'qq', 'version': 'pp'}
INFO:app:fggg
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:55:52] "POST /download_registry_model HTTP/1.1" 200 -
INFO:app:{'model_name': 'qq', 'version': 'pp'}
INFO:app:fggg
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:55:57] "POST /download_registry_model HTTP/1.1" 200 -
INFO:app:{'model_name': 'qq', 'version': 'pp'}
INFO:app:fggg
INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:56:02] "POST /download_registry_model HTTP/1.1" 200 -
INFO:app:{'model_name': 'qq', 'version': 'pp'}
INFO:app:./models/
INFO:werkzeug:127.0.0.1 - - [04/Dec/2023 00:06:41] "POST /download_registry_model HTTP/1.1" 200 -
INFO:app:{'model_name': 'qq', 'version': 'pp'}
INFO:app:No
INFO:werkzeug:127.0.0.1 - - [04/Dec/2023 00:12:53] "POST /download_registry_model HTTP/1.1" 200 -
INFO:app:{'model_name': 'log_reg_shot_dist_and_angle', 'version': 'pp'}
INFO:app:yes
INFO:werkzeug:127.0.0.1 - - [04/Dec/2023 00:13:07] "POST /download_registry_model HTTP/1.1" 200 -
INFO:app:{'model_name': 'log_reg_shot_dist_and_angle', 'version': 'pp'}
INFO:app:yes
INFO:werkzeug:127.0.0.1 - - [04/Dec/2023 00:20:35] "POST /download_registry_model HTTP/1.1" 200 -
